[package]
name = "git_mob"
version = "0.1.0"
authors = ["Martin Frost <martin@frost.ws>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dirs = "2.0"
git2 = "0.13"
serde = { version =  "1.0", features = ["derive"] }
serde_json = "1.0"
structopt = "0.3"
