on: workflow_dispatch

name: Build packages

jobs:
  build_deb:
    name: Build .deb package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - run: cargo install cargo-deb
      - run: cargo deb
      - uses: actions/upload-artifact@v2
        with:
          path: target/debian/*.deb
