on: workflow_dispatch

name: Build packages

jobs:
  build_deb:
    name: Build .deb package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - run: cargo install cargo-deb
      - run: cargo build --release
      - run: ./prepare-release.sh
      - run: cargo deb
      - uses: actions/upload-artifact@v3
        with:
          path: target/debian/*.deb
