on: workflow_dispatch

name: Build packages

jobs:
  build_deb:
    name: Build .deb package
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: "-C strip=debuginfo"
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo install cargo-deb
      - run: cargo build --release
      - run: cargo deb
      - uses: actions/upload-artifact@v4
        with:
          path: target/debian/*.deb
